stages:
  create_data_dir:
    cmd: mkdir -p data
  extract:
    foreach: 
      - sp500_targets
      - news_headlines
    do:
      cmd:
        - python -m src.extract --output ${item}
      outs:
        - data/${item}.parquet
